name: twitter_oembed_api
description: This library provides the easiest way to use the Twitter oEmbed API in Dart and Flutter apps.
version: 0.1.0
repository: https://github.com/twitter-dart/twitter-oembed-api
issue_tracker: https://github.com/twitter-dart/twitter-oembed-api/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^1.1.0
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  import_sorter: ^4.6.0
